import { REDBARON_GAMES } from "./games";

// Standalone vanity page: two specific 2025 Astros box scores as their
// rendered social-image PNGs (generated by scripts/gen-redbaron77-images.ts
// into public/redbaron77/). Shows the images, not live HTML. Not linked
// from anywhere.

export const metadata = {
  title: "boxscore",
  robots: { index: false, follow: false },
};

export default function RedBaron77() {
  return (
    <div style={{ background: "#e9e5da", padding: "28px 16px", minHeight: "100vh" }}>
      <div style={{ maxWidth: 620, margin: "0 auto", display: "flex", flexDirection: "column", gap: 28 }}>
        {REDBARON_GAMES.map((g) => (
          /* eslint-disable-next-line @next/next/no-img-element */
          <img
            key={g.file}
            src={`/redbaron77/${g.file}`}
            alt="boxscore box score"
            style={{ width: "100%", height: "auto", display: "block", boxShadow: "0 2px 10px rgba(0,0,0,0.12)" }}
          />
        ))}
      </div>
    </div>
  );
}
