// Regenerates lib/tlds.ts from IANA's authoritative TLD list — the source of
// truth for "is this a real top-level domain." Used by validateEmail to reject
// addresses like foo@bar.con (.con is not a TLD). Run occasionally to pick up
// new TLDs; the list changes rarely.
//
// Run: npx tsx scripts/update-tlds.ts

import { writeFile } from "node:fs/promises";

const SRC = "https://data.iana.org/TLD/tlds-alpha-by-domain.txt";

async function main() {
  const res = await fetch(SRC);
  if (!res.ok) throw new Error(`fetch IANA TLDs: ${res.status}`);
  const text = await res.text();

  const versionLine = text.split("\n")[0] ?? "";
  const tlds = text
    .split("\n")
    .filter((l) => l && !l.startsWith("#"))
    .map((l) => l.trim().toLowerCase())
    .filter(Boolean)
    .sort();

  const out =
    `// Generated by scripts/update-tlds.ts from ${SRC}\n` +
    `// ${versionLine.replace(/^#\s*/, "")}\n` +
    `// Authoritative set of valid TLDs (lowercased, incl. punycode IDN TLDs).\n` +
    `export const VALID_TLDS: ReadonlySet<string> = new Set([\n` +
    tlds.map((t) => `  ${JSON.stringify(t)},`).join("\n") +
    `\n]);\n`;

  await writeFile(new URL("../lib/tlds.ts", import.meta.url), out);
  console.log(`wrote lib/tlds.ts with ${tlds.length} TLDs (${versionLine.replace(/^#\s*/, "")})`);
}

main().catch((e) => { console.error(e); process.exit(1); });
