import { NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabase";

// Self-hosted open-tracking pixel. Gmail clips messages over ~102 KB,
// hiding Resend's end-of-body tracking pixel for the MLB league digest
// (~250-305 KB). This endpoint serves a 1x1 transparent GIF and records
// an open event so we can capture engagement that Resend misses.
//
// URL shape: /api/o/<sends.open_token>  — token is a UUID generated by
// the send cron BEFORE rendering, stored on the corresponding sends row.
//
// What gets recorded: a row in email_events with event_type='boxscore.opened'
// and resend_id pointing at the matching send. The read paths (getKpis,
// daily-metrics, charts) union 'email.opened' (Resend) with this event
// type so the existing UI surfaces include both.
//
// What we DON'T do: rate-limit per token, dedupe per IP, treat Mail-
// Privacy-Protection prefetches differently. The MPP/prefetch issue
// applies to Resend's pixel too — same caveat, same data. The pixel
// just needs to fire when the email is opened.

// Pre-encoded 1x1 transparent GIF (43 bytes). Faster than generating on
// every request and avoids a buffer alloc per fetch.
const TRANSPARENT_GIF = Buffer.from(
  "R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",
  "base64",
);

// Standard headers for a never-cache-but-fire-fast image. Image clients
// (Gmail proxy, Apple MPP, etc.) honor Cache-Control on the first fetch;
// no-store means each new send's pixel actually fetches our endpoint
// even if a similar URL was cached from a previous send.
const PIXEL_HEADERS = {
  "Content-Type": "image/gif",
  "Content-Length": String(TRANSPARENT_GIF.length),
  "Cache-Control": "private, no-store, no-cache, max-age=0, must-revalidate",
  "Pragma": "no-cache",
  "Expires": "0",
};

// Loose UUID-v4 shape. We don't strictly enforce v4 — Postgres
// gen_random_uuid() returns v4 but we want to be forgiving on the input
// (lowercase, hyphens). Rejecting obvious garbage saves a DB roundtrip.
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

function pixelResponse(): Response {
  return new NextResponse(TRANSPARENT_GIF as unknown as BodyInit, {
    status: 200,
    headers: PIXEL_HEADERS,
  });
}

export async function GET(
  request: Request,
  { params }: { params: Promise<{ token: string }> },
): Promise<Response> {
  const { token: rawToken } = await params;
  // Strip a trailing .gif if present — we encourage looking-like-an-image
  // URLs in the email template, and some inbox proxies fetch the URL
  // verbatim from the src attribute.
  const token = rawToken.replace(/\.gif$/i, "");

  // Always return the pixel even if the token is malformed or unknown.
  // An email client that fetched the URL deserves a valid image response
  // regardless — failing visibly would just be a broken image at the top
  // of the digest. Track-or-not is internal; pixel is public.
  if (!UUID_RE.test(token)) return pixelResponse();

  try {
    const db = supabaseAdmin();
    // Resolve token → resend_id. We log against resend_id so the existing
    // open-rate aggregation (which keys on resend_id) sees both Resend's
    // events and ours under one identifier.
    const { data: send } = await db
      .from("sends")
      .select("resend_id")
      .eq("open_token", token)
      .maybeSingle<{ resend_id: string | null }>();
    const resendId = send?.resend_id ?? null;
    if (!resendId) {
      // Token doesn't resolve, or the send row exists without a resend_id
      // (cron failure mid-flight). Pixel still fires; we just can't bind
      // the open to a known send. Skip the insert.
      return pixelResponse();
    }

    // User-agent + truncated IP for forensic debugging if a recipient
    // claims they opened/didn't open. Same /24 IPv4 + /48 IPv6 truncation
    // pattern email_events documents.
    const ua = request.headers.get("user-agent");
    const ip = truncatedClientIp(request.headers);

    await db.from("email_events").insert({
      resend_id: resendId,
      event_type: "boxscore.opened",
      user_agent: ua,
      ip,
      payload: { source: "self-hosted-pixel", token },
    });
  } catch (e) {
    // Don't fail the pixel fetch on a logging error — the user already
    // opened; we just lose this one data point. Surfacing the error to
    // an image client would do nothing useful.
    console.error(`pixel fetch logging failed: ${(e as Error).message}`);
  }

  return pixelResponse();
}

// Vercel / standard reverse proxies forward client IPs in
// x-forwarded-for. Strip to /24 (IPv4) or /48 (IPv6) so we never store
// the full address. Returns null when no usable header is present.
function truncatedClientIp(headers: Headers): string | null {
  const fwd = headers.get("x-forwarded-for") ?? headers.get("x-real-ip");
  if (!fwd) return null;
  const first = fwd.split(",")[0]?.trim();
  if (!first) return null;
  if (first.includes(":")) {
    // IPv6 → first 3 groups (48 bits)
    const parts = first.split(":");
    return parts.slice(0, 3).join(":") + "::";
  }
  // IPv4 → first 3 octets (24 bits)
  const parts = first.split(".");
  if (parts.length !== 4) return first;
  return `${parts[0]}.${parts[1]}.${parts[2]}.0/24`;
}
